# Generated by Django 4.1.7 on 2023-03-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorysubscribe',
            old_name='subcribe',
            new_name='subscribe',
        ),
    ]
